apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: liberty4all
  namespace: jconallen
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: liberty4all
    spec:
      containers:
      - name: liberty4all
        image: jconallen/liberty4all
        ports:
        - containerPort: 9080
        livenessProbe:
          httpGet:
            path: /health
            port: 9080
          initialDelaySeconds: 3
          periodSeconds: 3
 