apiVersion: v1
kind: Service
metadata:
  name: liberty4all-kad
  labels:
    app: liberty4all-kad
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9080
  selector:
    app: liberty4all-kad
